/// Flutter icons SocialMediaButtons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SocialMediaButtons
///      fonts:
///       - asset: fonts/SocialMediaButtons.ttf
///
/// 
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Brandico, (C) 2012 by Vitaly Puzrin
///         Author:    Crowdsourced, for Fontello project
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  
///
import 'package:flutter/widgets.dart';

class SocialMediaButtons {
  SocialMediaButtons._();

  static const _kFontFam = 'SocialMediaButtons';

  static const IconData stackoverflow = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData twitter = const IconData(0xf099, fontFamily: _kFontFam);
  static const IconData github_circled = const IconData(0xf09b, fontFamily: _kFontFam);
  static const IconData linkedin = const IconData(0xf0e1, fontFamily: _kFontFam);
  static const IconData instagram = const IconData(0xf16d, fontFamily: _kFontFam);
  static const IconData stackexchange = const IconData(0xf18d, fontFamily: _kFontFam);
  static const IconData spotify = const IconData(0xf1bc, fontFamily: _kFontFam);
  static const IconData github_squared = const IconData(0xf300, fontFamily: _kFontFam);
  static const IconData twitter_squared = const IconData(0xf304, fontFamily: _kFontFam);
  static const IconData linkedin_squared = const IconData(0xf30c, fontFamily: _kFontFam);
  static const IconData instagram_1 = const IconData(0xf31e, fontFamily: _kFontFam);
}
