name: Flutter Web
on:
  push:
    branches:
      - development
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-beta
        with:
          token: ${{secrets.commit_secret}}
      - run: |
          cd build/web
          git global --local user.email onatcipli@outlook.com
          git global --local user.name onatcipli
          git init
          git status
          git remote add origin https://github.com/onatcipli/onatcipli.github.io.git
          ls
          git add --all
          ls
          git commit -m "update"
          ls
          git push origin master -ff
