name: Flutter Web
on:
  push:
    branches:
      - development
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2-beta
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build web --release
      - run: |
          cd build/web
          git config --local user.email "onatcipli@outlook.com"
          git config --local user.name "Onat Çipli"
          git init
          git status
          git remote add origin https://github.com/onatcipli/onatcipli.github.io.git
          ls
          git add --all
          ls
          git commit -m "update"
          ls
          git push origin master -ff
